version: "3.9"
services:
  web:
    image: yuhonas/pear-store-backend:v1.0
    # build: web
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    # volumes:
    #   - .:/src
    depends_on:
      - db
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
